services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    restart: always
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 8180:80
    restart: always
  wordpress:
    depends_on:
      - db
      - phpmyadmin
    image: wordpress:latest
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
    ports:
      - 8080:80
    volumes:
      - ./wordpress:/var/www/html
    restart: always